apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bbregserver.name }}
  labels:
    app: {{ .Values.bbregserver.name }}
    group: {{ .Values.bbregserver.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.bbregserver.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.bbregserver.name }}
        group: {{ .Values.bbregserver.group }}
    spec:
      volumes:
        - name: {{ .Values.bbregserver.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.bbregserver.volume.pvc.name }}
      containers:
        - name: {{ .Values.bbregserver.name }}
          image: {{ .Values.bbregserver.container.image }}
          imagePullPolicy: {{ .Values.bbregserver.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.bbregserver.container.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          volumeMounts:
              - name: {{ .Values.bbregserver.volume.name }}
                mountPath: {{ .Values.bbregserver.volume.mountPath }}
                subPath: {{ .Values.bbregserver.volume.subPath }}