##################################################################################
# BitBroker docker compose
##################################################################################

version: "3"

networks:
  default:
    name: bbk-net

volumes:
  dbdata:

services:

  # --- coordinator service
  bbk-coordinator:
    build:
      context: ../..
      dockerfile: ./build/coordinator/Dockerfile
    container_name: bbk-coordinator
    image: bbk-coordinator
    depends_on:
      bbk-database:
        condition: service_healthy
      bbk-policy-cache:
        condition: service_healthy
    ports:
      - 8001:8001

  # --- contributor service
  bbk-contributor:
    build:
      context: ../..
      dockerfile: ./build/contributor/Dockerfile
    container_name: bbk-contributor
    image: bbk-contributor
    depends_on:
      bbk-database:
        condition: service_healthy
    ports:
      - 8002:8002

  # --- consumer service
  bbk-consumer:
    build:
      context: ../..
      dockerfile: ./build/consumer/Dockerfile
    container_name: bbk-consumer
    image: bbk-consumer
    depends_on:
      bbk-database:
        condition: service_healthy
    ports:
      - 8003:8003

  # --- rate limit service
  bbk-rate-limit:
    build:
      context: ../../..
      dockerfile: ./bit-broker/build/rate-limit/Dockerfile
    container_name: bbk-rate-limit
    image: bbk-rate-limit
    depends_on:
      - bbk-rate-limit-cache
    ports:
      - 4000:4000
      - 7000:7000

  # --- main database
  bbk-database:
    image: postgis/postgis:13-3.1-alpine
    container_name: bbk-database
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ../../database/schema.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ../../database/tests.sql:/docker-entrypoint-initdb.d/2-init.sql
    environment:
      POSTGRES_PASSWORD: "bitbr0ker"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 4s
      timeout: 4s
      retries: 16

  # --- policy cache
  bbk-policy-cache:
    image: redis:6.2.3-alpine
    container_name: bbk-policy-cache
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 4s
      timeout: 4s
      retries: 16

  # --- rate limit cache
  bbk-rate-limit-cache:
    image: redis:6.2.3-alpine
    container_name: bbk-rate-limit-cache
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 4s
      timeout: 4s
      retries: 16
