##################################################################################
# Name:        docker-compose.yml
##################################################################################

version: "3"
services:
  # Bitbroker Coordinator
  bitbroker-coordinator:
    build:
      context: ../..
      dockerfile: ./build/coordinator/Dockerfile
    container_name: bitbroker-coordinator
    image: bitbroker-coordinator
    depends_on:
      - bitbroker-db
    ports:
      - 8001:8001

  # Bitbroker Contributor
  bitbroker-contributor:
    build:
      context: ../..
      dockerfile: ./build/contributor/Dockerfile
    container_name: bitbroker-contributor
    image: bitbroker-contributor
    depends_on:
      - bitbroker-db
    ports:
      - 8002:8002

  # Bitbroker Consumer
  bitbroker-consumer:
    build:
      context: ../..
      dockerfile: ./build/consumer/Dockerfile
    container_name: bitbroker-consumer
    image: bitbroker-consumer
    depends_on:
      - bitbroker-db
    ports:
      - 8003:8003

  # Policy server
  bitbroker-policy:
    build:
      context: ../..
      dockerfile: ./build/policy/Dockerfile
    container_name: bitbroker-policy
    image: bitbroker-policy
    depends_on:
      - bitbroker-db
    ports:
      - 8004:8004

  # The Database
  bitbroker-db:
    image: postgres:13.2
    container_name: bitbroker-db
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ../../database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "bitbr0ker"
    ports:
      - "5432:5432"

  # Policy Cache
  bitbroker-policy-cache:
    image: redis:6.2.3-alpine
    container_name: bitbroker-policy-cache
    ports:
      - 6379:6379

networks:
  default:
    name: bitbroker-net

volumes:
  dbdata:
