replicaCount: 1
postgres:
  name: bitbroker-db
  group: db
  container:
    image: public.ecr.aws/y1v9w5g2/bitbroker-db:latest
    name: bitbroker-db
    port: 5432
  imagePullSecrets: ecrcred
  service:
    type: ClusterIP
    port: 5432
    nodeport: 30001
  volume:
    name: postgres-storage
    kind: PersistentVolumeClaim
    mountPath: /var/lib/postgresql/data
    subPath: postgres
    pvc:
      name: postgres-persistent-volume-claim
      accessMode: ReadWriteOnce
      storage: 4Gi

postgres_password: 'bitbr0ker'