##################################################################################
# BitBroker docker compose
##################################################################################

version: "3"

networks:
  default:
    name: bbk-net

volumes:
  dbdata:

services:

  # --- coordinator service
  bbk-coordinator:
    build:
      context: ../..
      dockerfile: ./build/coordinator/Dockerfile
    container_name: bbk-coordinator
    image: bbk-coordinator
    depends_on:
      bbk-database:
        condition: service_healthy
      bbk-policy-cache:
        condition: service_healthy
      bbk-auth-service:
        condition: service_healthy
    ports:
      - 8001:8001
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:8001/v1 -q --spider"]
      interval: 4s
      timeout: 4s
      retries: 4

  # --- contributor service
  bbk-contributor:
    build:
      context: ../..
      dockerfile: ./build/contributor/Dockerfile
    container_name: bbk-contributor
    image: bbk-contributor
    depends_on:
      bbk-database:
        condition: service_healthy
    ports:
      - 8002:8002
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:8002/v1 -q --spider"]
      interval: 4s
      timeout: 4s
      retries: 4

  # --- consumer service
  bbk-consumer:
    build:
      context: ../..
      dockerfile: ./build/consumer/Dockerfile
    container_name: bbk-consumer
    image: bbk-consumer
    depends_on:
      bbk-database:
        condition: service_healthy
    ports:
      - 8003:8003
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:8003/v1 -q --spider"]
      interval: 4s
      timeout: 4s
      retries: 4

  # --- main database
  bbk-database:
    image: postgis/postgis:13-3.1-alpine
    container_name: bbk-database
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ../../database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "bitbr0ker"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", 'psql -U postgres -lqt | cut -d \| -f 1 | grep -qw bit_broker']
      interval: 4s
      timeout: 4s
      retries: 4

  # --- rate limit service
  bbk-rate-limit:
    build:
      context: ../../..
      dockerfile: ./bit-broker/development/ancillary-services/rate-limit/Dockerfile
    container_name: bbk-rate-limit
    image: bbk-rate-limit
    depends_on:
      bbk-rate-limit-cache:
        condition: service_healthy
    ports:
      - 4000:4000
      - 7000:7000
    healthcheck:
      test: ["CMD-SHELL", 'ls']
      interval: 4s
      timeout: 4s
      retries: 4

  # --- rate limit cache
  bbk-rate-limit-cache:
    image: redis:6.2.3-alpine
    container_name: bbk-rate-limit-cache
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 4s
      timeout: 4s
      retries: 4

  # --- auth service
  bbk-auth-service:
    build:
      context: ../../..
      dockerfile: ./bit-broker/development/ancillary-services/auth-service/Dockerfile
    container_name: bbk-auth-service
    image: bbk-auth-service
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:8080/api/v1 -q --spider"]
      interval: 4s
      timeout: 4s
      retries: 4

  # --- policy cache
  bbk-policy-cache:
    image: redis:6.2.3-alpine
    container_name: bbk-policy-cache
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 4s
      timeout: 4s
      retries: 4
