name: Build and test
on:
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
   
  build-test:
    runs-on: ubuntu-latest
    steps:
       
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      #update etc/hosts to resolve service names
      - name: Add hosts to /etc/hosts
        run: |
          echo "10.0.2.15	bbk-coordinator" | sudo tee -a /etc/hosts
          echo "10.0.2.15	bbk-contributor" | sudo tee -a /etc/hosts
          echo "10.0.2.15	bbk-consumer" | sudo tee -a /etc/hosts
          echo "10.0.2.15	bbk-database" | sudo tee -a /etc/hosts
          echo "10.0.2.15	bbk-policy-cache" | sudo tee -a /etc/hosts
          echo "10.0.2.15	bbk-auth-service" | sudo tee -a /etc/hosts
          echo "10.0.2.15	bbk-rate-limit" | sudo tee -a /etc/hosts
          echo "10.0.2.15	bbk-webhook" | sudo tee -a /etc/hosts

      # set up env files required for deployment & test...
      - name: Create .env file for docker
        run: cp .env.example .env

      - name: Create .env file for tests
        run: cp .env.example ./tests/.env

      # install test suite dependencies
      - name: install dependencies
        working-directory: tests 
        run: npm install
       
      - name: build and run docker-compose
        working-directory: development/docker-compose
        run: docker-compose up --build -d

      - name: run tests
        working-directory: tests 
        run: node all.js

      - name: Stop containers
        if: always()
        working-directory: development/docker-compose
        run: docker-compose down