name: Publish Image to Docker Registry

on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Parse tag name
      run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3 | cut -c2-)" >> $GITHUB_ENV

    # Login and push to AWS ECR
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Push coordinator image to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/coordinator/Dockerfile
        tags: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/coordinator:latest,${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/coordinator:${{ env.TAG_NAME }}
    - name: Push consumer image to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/consumer/Dockerfile
        tags: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/consumer:latest,${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/consumer:${{ env.TAG_NAME }}
    - name: Push contributor image to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/contributor/Dockerfile
        tags: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/contributor:latest,${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/contributor:${{ env.TAG_NAME }}
    - name: Push policy image to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/policy/Dockerfile
        tags: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/policy:latest,${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/policy:${{ env.TAG_NAME }}

