# Copyright 2022 Cisco and its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Publish Image to Docker Registry

on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Parse tag name
      run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3 | cut -c2-)" >> $GITHUB_ENV

    # Login and push to AWS ECR
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Push coordinator image to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/coordinator/Dockerfile
        tags: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/bbk-coordinator:latest,${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/bbk-coordinator:${{ env.TAG_NAME }}
    - name: Push consumer image to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/consumer/Dockerfile
        tags: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/bbk-consumer:latest,${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/bbk-consumer:${{ env.TAG_NAME }}
    - name: Push contributor image to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/contributor/Dockerfile
        tags: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/bbk-contributor:latest,${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/bbk-contributor:${{ env.TAG_NAME }}
    - name: Push flyway migrator image to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./build/flyway/Dockerfile
        tags: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/bbk-flyway-migrate:latest,${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/bbk-flyway-migrate:${{ env.TAG_NAME }}
